artifact_location: /Users/selinsevim/Desktop/predictive_maintenance_rul_battery_model/ml_runs/903115369020944047
creation_time: 1751036440520
experiment_id: '903115369020944047'
last_update_time: 1751036440520
lifecycle_stage: active
name: batter_predictive_01
