artifact_uri: /Users/selinsevim/Desktop/predictive_maintenance_rul_battery_model/ml_runs/674273899611329442/41f45653823a42a1baa32bc12ade7281/artifacts
end_time: 1750766808419
entry_point_name: ''
experiment_id: '674273899611329442'
lifecycle_stage: active
run_id: 41f45653823a42a1baa32bc12ade7281
run_name: worried-horse-798
source_name: ''
source_type: 4
source_version: ''
start_time: 1750766590580
status: 3
tags: []
user_id: selinsevim
