artifact_location: /Users/selinsevim/Desktop/predictive_maintenance_rul_battery_model/ml_runs/674273899611329442
creation_time: 1750766590571
experiment_id: '674273899611329442'
last_update_time: 1750766590571
lifecycle_stage: active
name: batter_predictive_01
