artifact_uri: /Users/selinsevim/Desktop/predictive_maintenance_rul_battery_model/ml_runs/674273899611329442/ca2fbfa255064092bafc3a368edd9d57/artifacts
end_time: 1750780107810
entry_point_name: ''
experiment_id: '674273899611329442'
lifecycle_stage: active
run_id: ca2fbfa255064092bafc3a368edd9d57
run_name: secretive-tern-993
source_name: ''
source_type: 4
source_version: ''
start_time: 1750779938765
status: 3
tags: []
user_id: selinsevim
